{{- if .Values.serviceAccount.create -}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "whereabouts.serviceAccountName" . }}
  labels:
    {{- include "whereabouts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "whereabouts.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "whereabouts.serviceAccountName" . }}
  {{- include "whereabouts.namespace" . | nindent 2 }}
{{- end }}
